- name: Bootstrap
  hosts: all
  become: true
  roles:
    - clickhouse
  vars:
    is_packer: true
    step_ca_url: "https://step-ca.us-homelab1.hl.rmb938.me"
    step_ra_acme_url: "https://step-ca.us-homelab1.hl.rmb938.me:8443"
